SCRIPTS: Consolidate the two decomp scripts

diff --git a/packages/seacas/scripts/decomp.in b/packages/seacas/scripts/decomp.in
--- a/packages/seacas/scripts/decomp.in
+++ b/packages/seacas/scripts/decomp.in
@@ -47,6 +47,7 @@ Decomposition methods: [0..3] = speed ranking 0=fastest
 
 Other options:
 --help              Print this message (-h)
+--noop              Only echo the nem_slice and nem_spread commands.
 --nodal             Nodal Decomposition (-N)
 --elemental         Elemental Decomposition (default, -E)
 --input <file>      Optional nem_slice input file (-i)
@@ -58,7 +59,7 @@ Other options:
 --subdir <sub_dir>  Continuation of the path on the separate disks to the files (-S)
 --spread_suffix <x> Suffix for parallel files (default: meshfile suffix) (-X)
 --64                Force creation of 64-bit integer decomposed files (-6)
--n <options>        Specify nem_slice options
+-n <options>        Specify additional nem_slice options
 
    Documentation: https://sandialabs.github.io/seacas-docs/sphinx/html/index.html#decomp"
    help-email: sierra-help@sandia.gov
@@ -70,7 +71,7 @@ exit 1
 function usage_old {
 cat <<DECOMP_USAGE_EOF
 Usage:  decomp [-h] -p <processor count> [-n <nemslice options>]
-               [-R <root directory>] [-S <sub directory]
+               [-R <root directory>] [-S <sub directory>] [-X <suffix>]
                [-l multikl] [-l spectral] [-l inertial] [-l linear]
                [-l rcb] [-l rcb_ignore_z] [-l rib] [-l hsfc] [-l random] [-l scattered]
                [...others...] meshfile.ext
@@ -155,31 +156,31 @@ function execute_loadbalance {
     # Check for valid executable...
     if [ ! -x $NEM_SLICE ]
     then
-	echo
-	echo ${txtred}
-	echo "ERROR: Could not find or execute $NEM_SLICE"
-	echo "ERROR: Configuration error"
-	echo ${txtrst}
-	echo
+        echo
+        echo ${txtred}
+        echo "ERROR: Could not find or execute $NEM_SLICE"
+        echo "ERROR: Configuration error"
+        echo ${txtrst}
+        echo
 
-	return -1
+        return -1
     fi
 
     if [ -n "$input" ] && [ -e "$input" ]
     then
-	echo ${txtblu}
-	echo "Executing:"
-	echo "   $NEM_SLICE $decomp_type $spheres $do_viz $decomp_method $weighting $nem_slice_flag -o $nemesis -m mesh=$processors -a $input $genesis"
-	echo ${txtrst}
-	($NEM_SLICE $decomp_type $spheres $do_viz $decomp_method $weighting $nem_slice_flag -o $nemesis -m mesh=$processors -a $input $genesis)
-	load_rc=$?
+        echo ${txtblu}
+        echo "Executing:"
+        echo "   $NEM_SLICE $decomp_type $spheres $do_viz $decomp_method $weighting $nem_slice_flag -o $nemesis -m mesh=$processors -a $input $genesis"
+        echo ${txtrst}
+        (${NOOP:+echo }$NEM_SLICE $decomp_type $spheres $do_viz $decomp_method $weighting $nem_slice_flag -o $nemesis -m mesh=$processors -a $input $genesis)
+        load_rc=$?
     else
-	echo ${txtblu}
-	echo "Executing:"
-	echo "   $NEM_SLICE $decomp_type $spheres $do_viz $decomp_method $weighting $nem_slice_flag -o $nemesis -m mesh=$processors $genesis"
-	echo ${txtrst}
-	($NEM_SLICE $decomp_type $spheres $decomp_method $do_viz $weighting $nem_slice_flag -o $nemesis -m mesh=$processors $genesis)
-	load_rc=$?
+        echo ${txtblu}
+        echo "Executing:"
+        echo "   $NEM_SLICE $decomp_type $spheres $do_viz $decomp_method $weighting $nem_slice_flag -o $nemesis -m mesh=$processors $genesis"
+        echo ${txtrst}
+        (${NOOP:+echo }$NEM_SLICE $decomp_type $spheres $do_viz $decomp_method $weighting $nem_slice_flag -o $nemesis -m mesh=$processors $genesis)
+        load_rc=$?
     fi
     return $load_rc
 }
@@ -201,28 +202,28 @@ function execute_spread {
     # Check for valid executable...
     if [ ! -x $NEM_SPREAD ]
     then
-	echo
-	echo ${txtred}
-	echo "ERROR: Could not find or execute $NEM_SPREAD"
-	echo "ERROR: Configuration error"
-	echo ${txtrst}
-	echo
-	return -1
+        echo
+        echo ${txtred}
+        echo "ERROR: Could not find or execute $NEM_SPREAD"
+        echo "ERROR: Configuration error"
+        echo ${txtrst}
+        echo
+        return -1
     fi
 
     if [ "$subdir" != "." ]
     then
-	dir=$rootdir/$subdir
-	if [ ! -e $dir ]
-	then
-	    echo "making directory $dir"
-	    mkdir -p $dir
-	fi
+        dir=$rootdir/$subdir
+        if [ ! -e $dir ]
+        then
+            echo "making directory $dir"
+            mkdir -p $dir
+        fi
     fi
 
     if [ -e $pexsh ]
     then
-	/bin/rm -rf $pexsh
+        /bin/rm -rf $pexsh
     fi
 
     echo "Input FEM file                   = $genesis"                  >  $pexsh
@@ -244,7 +245,7 @@ function execute_spread {
     echo "Executing:"
     echo "   $NEM_SPREAD $use64 $pexsh"
     echo ${txtrst}
-    $NEM_SPREAD $use64 $pexsh
+    ${NOOP:+echo }$NEM_SPREAD $use64 $pexsh
 }
 
 ########################################################################
@@ -288,6 +289,8 @@ suffix_spread=''
 spheres="-S"
 do_viz=""
 use64=""
+
+NOOP=
 
 if [ "$ACCESS" == "" ]
 then
@@ -341,9 +344,35 @@ fi
 if [ $OLDGETOPT -eq 1 ] ; then
    TEMP=$(getopt Hh6ENn:i:o:p:j:r:R:S:X:sl:vVd: "$@")
 else
-    TEMP=$(getopt -o Hh6ENn:i:o:p:j:r:R:S:X:sl:vVd:w: -a \
-       --long input:,help,nem_slice_flag,64,processors:,rootdir:,subdir:,spread_suffix:,spheres_linear,viz_mesh,verbose,debug:,nodal,elemental \
-       --long multikl,rcb,rcb_ignore_z,rib,hsfc,spectral,inertial,linear,random,scattered,brick,zpinch,weight: \
+   TEMP=$(getopt -o Hh6ENn:i:o:p:j:r:R:S:X:sl:vVd:w: -a \
+       --long input: \
+       --long noop \
+       --long help \
+       --long nem_slice_flag \
+       --long 64 \
+       --long processors: \
+       --long rootdir: \
+       --long subdir: \
+       --long spread_suffix: \
+       --long spheres_linear \
+       --long viz_mesh \
+       --long verbose \
+       --long debug: \
+       --long nodal \
+       --long elemental \
+       --long multikl \
+       --long rcb \
+       --long rcb_ignore_z \
+       --long rib \
+       --long hsfc \
+       --long spectral \
+       --long inertial \
+       --long linear \
+       --long random \
+       --long scattered \
+       --long brick \
+       --long zpinch \
+       --long weight: \
        -n 'decomp' -- "$@")
 fi
 
@@ -352,56 +381,58 @@ if [ $? != 0 ] ; then usage ; exit 1 ; fi
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
 while true ; do
-	case "$1" in
-	    -h|-H|--help)
-	      usage_new ; shift ;;
-	    -v|--verbose)
-	      set -x ; shift ;;
-	    -V|--viz_mesh)
-	      do_viz="-y" ; shift ;;
-	    -d|--debug)
-	      debug_level="$2" ; shift 2 ;;
-	    -n|--nem_slice_flag)
-	      nem_slice_flag="$2" ; shift 2 ;;
-            -N|--nodal)
-	      decomp_type="-n" ; shift ;;
-            -E|--elemental)
-              decomp_type="-e" ; shift ;;
-	    -i|--input)
-	      input=$2 ; shift 2 ;;
-	    -w|--weight)
-	      weighting="-w $2" ; shift 2 ;;
-	    -p|-j|--processors)
-	      processors=$2 ; shift 2 ;;
-	    -R|--rootdir)
-	      rootdir=$2 ; shift 2 ;;
-	    -S|--subdir)
-	      subdir=$2 ; shift 2 ;;
-	    -X|--spread_suffix)
-	      suffix_spread=$2 ; shift 2 ;;
-	    -s|--spheres_linear)
-	      spheres="" ; shift ;;
-	    -6|--64)
-	      use64="-64" ; shift ;;
-	    -l)
-	      decomp_method="-l $2" ; shift 2 ;;
+    case "$1" in
+    (-h|-H|--help)
+        usage_new ; shift ;;
+    (-v|--verbose)
+        set -x ; shift ;;
+    (-V|--viz_mesh)
+        do_viz="-y" ; shift ;;
+    (-d|--debug)
+        debug_level="$2" ; shift 2 ;;
+    (-n|--nem_slice_flag)
+        nem_slice_flag="$2" ; shift 2 ;;
+    (-N|--nodal)
+        decomp_type="-n" ; shift ;;
+    (-E|--elemental)
+        decomp_type="-e" ; shift ;;
+    (-i|--input)
+        input=$2 ; shift 2 ;;
+    (-w|--weight)
+        weighting="-w $2" ; shift 2 ;;
+    (-p|-j|--processors)
+        processors=$2 ; shift 2 ;;
+    (-R|--rootdir)
+        rootdir=$2 ; shift 2 ;;
+    (-S|--subdir)
+        subdir=$2 ; shift 2 ;;
+    (-X|--spread_suffix)
+        suffix_spread=$2 ; shift 2 ;;
+    (-s|--spheres_linear)
+        spheres="" ; shift ;;
+    (-6|--64)
+        use64="-64" ; shift ;;
+    (--noop)
+        NOOP="--noop" ; shift ;;
+    (-l)
+        decomp_method="-l $2" ; shift 2 ;;
 
 # Decomposition Method options...
-	    --multikl)   decomp_method="-l multikl" ; shift ;;
-	    --rcb)       decomp_method="-l rcb" ; shift ;;
-	    --rcb_ignore_z)       decomp_method="-l rcb,ignore_z" ; shift ;;
-	    --rib)       decomp_method="-l rib" ; shift ;;
-	    --hsfc)      decomp_method="-l hsfc" ; shift ;;
-	    --spectral)  decomp_method="-l spectral" ; shift ;;
-	    --inertial)  decomp_method="-l inertial" ; shift ;;
-	    --linear)    decomp_method="-l linear" ; shift ;;
-	    --random)    decomp_method="-l random" ; shift ;;
-	    --scattered) decomp_method="-l scattered" ; shift ;;
-	    --brick)     decomp_method="-l brick" ; shift ;;
-	    --zpinch)    decomp_method="-l zpinch" ; shift ;;
-	    --) shift ; break ;;
-	    *) echo "${txtred}ERROR: unrecognized option $1${txtrst}" ; shift ;;
-	esac
+    (--multikl)   decomp_method="-l multikl" ; shift ;;
+    (--rcb)       decomp_method="-l rcb" ; shift ;;
+    (--rcb_ignore_z)       decomp_method="-l rcb,ignore_z" ; shift ;;
+    (--rib)       decomp_method="-l rib" ; shift ;;
+    (--hsfc)      decomp_method="-l hsfc" ; shift ;;
+    (--spectral)  decomp_method="-l spectral" ; shift ;;
+    (--inertial)  decomp_method="-l inertial" ; shift ;;
+    (--linear)    decomp_method="-l linear" ; shift ;;
+    (--random)    decomp_method="-l random" ; shift ;;
+    (--scattered) decomp_method="-l scattered" ; shift ;;
+    (--brick)     decomp_method="-l brick" ; shift ;;
+    (--zpinch)    decomp_method="-l zpinch" ; shift ;;
+    (--) shift ; break ;;
+    (*) echo "${txtred}ERROR: unrecognized option $1${txtrst}" ; shift ;;
+    esac
 done
 
 ########################################################################
@@ -417,22 +448,22 @@ if [ $# -eq 0 ] ; then
 else
     if [ -e "$1" ]
     then
-	file=$1
-	suffix_mesh=${file##*.}
-  if test -z "$suffix_spread"
-  then
-    suffix_spread=$suffix_mesh
-  fi
-	basename=${file%.*}
+        file=$1
+        suffix_mesh=${file##*.}
+        if test -z "$suffix_spread"
+        then
+            suffix_spread=$suffix_mesh
+        fi
+        basename=${file%.*}
     else
     echo ${txtred}
-	echo "ERROR:******************************************************************"
-	echo "ERROR:"
-	echo "ERROR: $1 does not exist."
-	echo "ERROR:"
-	echo "ERROR:******************************************************************"
-	echo ${txtrst}
-	usage
+        echo "ERROR:******************************************************************"
+        echo "ERROR:"
+        echo "ERROR: $1 does not exist."
+        echo "ERROR:"
+        echo "ERROR:******************************************************************"
+        echo ${txtrst}
+        usage
     fi
 fi
 
@@ -441,28 +472,28 @@ then
    if [ ! -e "$input" ]
    then
     echo ${txtred}
-	echo "ERROR:******************************************************************"
-	echo "ERROR:"
-	echo "ERROR: Input file $input does not exist."
-	echo "ERROR:"
-	echo "ERROR:******************************************************************"
-	echo ${txtrst}
-	usage
+        echo "ERROR:******************************************************************"
+        echo "ERROR:"
+        echo "ERROR: Input file $input does not exist."
+        echo "ERROR:"
+        echo "ERROR:******************************************************************"
+        echo ${txtrst}
+        usage
    fi
 fi
 
 if test -z "$processors"
 then
-  echo
-  echo ${txtred}
-  echo "ERROR:***************************************************"
-  echo "ERROR:"
-  echo "ERROR: Must specify number of processors --processors (-p -j) option"
-  echo "ERROR:"
-  echo "ERROR:***************************************************"
-  echo ${txtrst}
-  echo
-  usage
+    echo
+    echo ${txtred}
+    echo "ERROR:***************************************************"
+    echo "ERROR:"
+    echo "ERROR: Must specify number of processors --processors (-p -j) option"
+    echo "ERROR:"
+    echo "ERROR:***************************************************"
+    echo ${txtrst}
+    echo
+    usage
 fi
 
 if [ $processors -eq 1 ]
